### ISSUE TITLE
Content-Length does not match if using non-ASCII characters

### ISSUE THREAD

**Issue by randomstuff** [stny/rack-emoji#1]
Using ruby 2.1, this code does not work correctly if non-ASCII characters are in the reponse:

``` ruby
headers['Content-Length'] = new_response.length.to_s
```

The reason, is that this gives the number of unicode characters, not the number of bytes:

<pre>
irb(main):002:0> "éé".length.to_s
=> "2"
irb(main):001:0> "éé".bytes.length.to_s
=> "4"
</pre>

This gives errors such as:

<pre>>> Thin web server (v1.3.1 codename Triple Espresso)
>> Maximum connections set to 1024
>> Listening on localhost:9292, CTRL+C to stop
!! Unexpected error while processing request: Content-Length header was 175, but should be 176
127.0.0.1 - - [04/Jul/2015:10:18:41 +0200] "GET / HTTP/1.1" 200 175 0.0192
</pre>

Something like this might be used instead:

``` ruby
headers['Content-Type'] = "text/html; charset=utf-8"
headers['Content-Length'] = new_response.bytes.length.to_s
```

**Comment by randomstuff** [comment]
See https://github.com/rack/rack-contrib/blob/master/lib/rack/contrib/backstage.rb:

``` ruby
length = "".respond_to?(:bytesize) ? content.bytesize.to_s : content.size.to_s
```

**Comment by stny** [comment]
Thank you for reporting :+1:
Let me check as soon as possible.
